### ISSUE TITLE
imprecise approximation of small elliptical arcs to quadratic curves

### ISSUE THREAD

**Issue by anthrotype** [rsheeter/nanosvg#1]
When converting a cicle or ellipsis to skia path with `nanosvg.svg_pathops.skia_path` function, we call `pathops.Path.convertConicsToQuads` method to approximate conic curves with quadratic bezier curves.

https://github.com/rsheeter/nanosvg/blob/061fe5e378a8746a70adf1b8c4ecfa20b16f2e5d/src/nanosvg/svg_pathops.py#L80

If the circle radius is relatively small, like in the example below, we end up with not enough quadratic segments to approximate a circle.

```xml
<svg viewBox="0 0 10 10" xmlns="http://www.w3.org/2000/svg">
  <circle cx="5" cy="5" r="4" fill="gold" />
</svg>
```

![image](https://user-images.githubusercontent.com/6939968/78823139-19bbff00-79d4-11ea-8fc4-e2874f17ff96.png)

If I increse the "resolution" of the svg user-space coordinates, the same circle renders fine when converted to quadratics:

```xml
<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
  <circle cx="50" cy="50" r="40" fill="gold" />
</svg>
```

![image](https://user-images.githubusercontent.com/6939968/78823481-ac5c9e00-79d4-11ea-81d2-0fddf3b8706f.png)

Cf convertConicsToQuads in skia-pathops:
https://github.com/fonttools/skia-pathops/blob/6758f1001ff2177daf7015f78cad98bc9c71deae/src/python/pathops/_pathops.pyx#L363

**Comment by anthrotype** [comment]
the first almost-circle dumps as

```
path.moveTo(1, 5)
path.quadTo(1, 1, 5, 1)
path.quadTo(9, 1, 9, 5)
path.quadTo(9, 9, 5, 9)
path.quadTo(1, 9, 1, 5)
path.close()
```

the second, more faithful circle dumps as:

```
path.moveTo(10, 50)
path.quadTo(10, 42.0435, 13.0448, 34.6927)
path.quadTo(16.0896, 27.3418, 21.7157, 21.7157)
path.quadTo(27.3418, 16.0896, 34.6927, 13.0448)
path.quadTo(42.0435, 10, 50, 10)
path.quadTo(57.9565, 10, 65.3073, 13.0448)
path.quadTo(72.6582, 16.0896, 78.2843, 21.7157)
path.quadTo(83.9104, 27.3418, 86.9552, 34.6927)
path.quadTo(90, 42.0435, 90, 50)
path.quadTo(90, 57.9565, 86.9552, 65.3073)
path.quadTo(83.9104, 72.6582, 78.2843, 78.2843)
path.quadTo(72.6582, 83.9104, 65.3073, 86.9552)
path.quadTo(57.9565, 90, 50, 90)
path.quadTo(42.0435, 90, 34.6927, 86.9552)
path.quadTo(27.3418, 83.9104, 21.7157, 78.2843)
path.quadTo(16.0896, 72.6582, 13.0448, 65.3073)
path.quadTo(10, 57.9565, 10, 50)
path.close()
```

**Comment by rsheeter** [comment]
My suspicion is that I passed it a fixed error margin and actually need to adjust it based on the viewbox definition just (sigh) as I did with the cu2qu pen.

**Comment by rsheeter** [comment]
```
# _pathops.pyx
    cpdef convertConicsToQuads(self, float tolerance=0.25):
     # TODO is 0.25 too delicate? - blindly copies from Skias own use
```

**Comment by rsheeter** [comment]
Fixed by 0094fab

Before:
<img width="148" alt="Screen Shot 2020-04-08 at 8 16 54 PM" src="https://user-images.githubusercontent.com/6466432/78854520-5e489a00-79d6-11ea-8684-09b3a8d4ff52.png">
After:
<img width="158" alt="Screen Shot 2020-04-08 at 8 16 49 PM" src="https://user-images.githubusercontent.com/6466432/78854521-5ee13080-79d6-11ea-90b8-58f41a7b08ac.png">

**Comment by anthrotype** [comment]
pity we have to pass down the tolerance every time we interact with pathops, but at least we get nice arcs now.

**Comment by rsheeter** [comment]
I considered trying to hide it more but ultimately felt that for any potentially lossy op indicating how to handle that is a fundamental part of using it and better not hidden.
